apiVersion: v1
kind: Pod
metadata:
  name: bothpod
  annotations:
    networks: '[  
	{ "name": "flannel-conf" },
        { "name": "macvlan-conf" }
    ]'
spec:
  containers:
  - name: bothpod
    command: ["/bin/bash", "-c", "sleep 2000000000000"]
    image: dougbtv/centos-network
    ports:
    - containerPort: 80
