---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: multus
  namespace: kube-system
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: kube-multus-cfg
  namespace: kube-system
  labels:
    tier: node
    app: multus
data:
  cni-conf.json: |
    {
      "name": "minion1-multus-demo-network",
      "type": "multus",
      "delegates": [
          {
            "type": "ipvlan",
            "if0": "eth0",
            "if0name": "north0",
            "createmac": true,
            "ipam": {
              "type": "host-local",
              "subnet": "10.244.10.0/24",
              "rangeStart": "10.244.10.131",
              "rangeEnd": "10.244.10.190",
              "routes": [
                { "dst": "0.0.0.0/0" }
              ],
              "gateway": "10.244.10.1"
            }
          },
          {
            "type": "ipvlan",
            "if0": "eth0:1",
            "if0name": "south0",
            "ipam": {
              "type": "host-local",
              "subnet": "10.244.10.0/24",
              "rangeStart": "10.244.10.100",
              "rangeEnd": "10.244.10.130",
              "routes": [
                { "dst": "0.0.0.0/0" }
              ],
              "gateway": "10.244.10.1"
            }
          },
          {
            "type": "flannel",
            "masterplugin": true,
            "delegate": {
              "isDefaultGateway": true
            }
          }
      ]
    }
  net-conf.json: |
    {
      "Network": "10.244.0.0/16",
      "Backend": {
        "Type": "ipvlan"
      }
    }
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kube-multus-ds
  namespace: kube-system
  labels:
    tier: node
    app: multus
spec:
  template:
    metadata:
      labels:
        tier: node
        app: multus
    spec:
      hostNetwork: true
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      serviceAccountName: multus
      containers:
      - name: kube-flannel
        image: quay.io/coreos/flannel:v0.7.0-amd64
        command: [ "/opt/bin/flanneld", "--ip-masq", "--kube-subnet-mgr" ]
        securityContext:
          privileged: true
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: run
          mountPath: /run
        - name: flannel-cfg
          mountPath: /etc/kube-flannel/
      - name: install-cni
        image: quay.io/coreos/flannel:v0.7.0-amd64
        command: [ "/bin/sh", "-c", "set -e -x; cp -f /etc/kube-flannel/cni-conf.json /etc/cni/net.d/10-multus.conf; while true; do sleep 3600; done" ]
        volumeMounts:
        - name: cni
          mountPath: /etc/cni/net.d
        - name: flannel-cfg
          mountPath: /etc/kube-flannel/
      volumes:
        - name: run
          hostPath:
            path: /run
        - name: cni
          hostPath:
            path: /etc/cni/net.d
        - name: flannel-cfg
          configMap:
            name: kube-multus-cfg

