apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: "web"
  annotations:
    cni: "weave,canal"
spec:
  containers:
  - name: nginx
    image: nginx:latest
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 6379
